### ISSUE TITLE
Deprecated Lambda managed policy

### ISSUE THREAD

**Issue by ramonbouckaert** [BAPostma/Loft#1]
When attempting to deploy using AWS CloudFormation, I get a `CREATE_FAILED` event on `EmailHandlerExecutionRole`. The error message is as follows:
`Policy arn:aws:iam::aws:policy/AWSLambdaFullAccess does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: 32156892-91c2-41ae-a75c-5eb90e5bfb77; Proxy: null)`

This is likely due to the managed policy `AWSLambdaFullAccess` having been deprecated on March 1st, and replaced with `AWSLambda_FullAccess` - https://docs.aws.amazon.com/lambda/latest/dg/access-control-identity-based.html

**Comment by BAPostma** [comment]
Thanks for your interest in Loft and your feedback @ramonbouckaert!
I was able to reproduce it and believe this issue has now been resolved. Please reopen this issue should you still be experiencing problems.
